language: perl
perl:
  - "5.8.1"
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "blead"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm -n DBI
  - build-dist
  - cd $BUILD_DIR
matrix:
  allow_failures:
    - perl: blead
